fs: Import SUSFS implementation for GKI kernels
Switched from gki-android14-5.15 to  gki-android13-5.15  branch
from https://gitlab.com/simonpunk/susfs4ksu

Fixes Compilation errors:

ld.lld: error: undefined symbol: susfs_is_sus_su_hooks_enabled
>>> referenced by open.c:416 (../fs/open.c:416)
>>>               vmlinux.o:(do_faccessat)
>>> referenced by open.c:416 (../fs/open.c:416)
>>>               vmlinux.o:(do_faccessat)
>>> referenced by stat.c:237 (../fs/stat.c:237)
>>>               vmlinux.o:(vfs_statx)
>>> referenced 3 more times

ld.lld: error: undefined symbol: susfs_sus_su_working_mode
>>> referenced by susfs.c:851 (../fs/susfs.c:851)
>>>               vmlinux.o:(susfs_get_sus_su_working_mode)
>>> referenced by susfs.c:851 (../fs/susfs.c:851)
>>>               vmlinux.o:(susfs_get_sus_su_working_mode)
>>> referenced by susfs.c:856 (../fs/susfs.c:856)
>>>               vmlinux.o:(susfs_sus_su)
>>> referenced 3 more times
  BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: Invalid argument
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: .btf.vmlinux.bin.o: unknown file type

This commit Ports SUSFS (Secure Userland Filesystem Support) from susfs4ksu project

Key features:

- Mount namespace tracking via CL_COPY_MNT_NS flags
- Zygote process detection for mount propagation

- OverlayFS integration hooks
- Procfs interfaces for namespace monitoring

- KernelSU-Next compatibility layer

This is a direct import of patch:
50_add_susfs_in_gki-android14-5.15.patch

Manually resolved conflicts in:

- fs/namespace.c (mount structure changes)

Signed-off-by: akm-04 <akmabrar04@gmail.com>